server:
  port: 8888
security:
  basic:
    enable: true
  user:
    name: gwj
    password: 123
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://gwj:123@localhost:${server.port}/eureka